<template>
    <v-app>
     <v-card>
      <v-card-title>立替金支払い請求フォーム</v-card-title>
      <v-card-text>
        <p>立替日</p>
        <v-text-field
          v-model="text1"
          label=""
          outlined
          required
        >
        </v-text-field>
        <p>内容</p>
        <v-text-field
          v-model="text1"
          label=""
          outlined
          required
        >
        </v-text-field>
        <p>立替者</p>
        <v-select
          :items="items"
          label=""
          outlined
        ></v-select>
        <p>対象者</p>
        <v-select
            v-model="value"
            :items="items"
            chips
            label=""
            multiple
            outlined
          ></v-select>
        <p>金額</p>
        <v-text-field
          v-model="text1"
          label=""
          outlined
          required
        >
        </v-text-field>
        <p>備考</p>
        <v-textarea
          solo
          name="input-7-4"
          label=""
          outlined
        ></v-textarea>
      </v-card-text>
      <v-divider></v-divider>
      <v-card-actions>
        <v-btn text @click="submit" block x-large>送信する</v-btn>
        <span v-if="success">送信成功！</span>
      </v-card-actions>
    </v-card>
    </v-app>
</template>